<?php

namespace AppBundle\Repository;

/**
 * CamisetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CamisetaRepository extends \Doctrine\ORM\EntityRepository
{
}
